# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Bazel Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [x86_64-linux, arm64-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ matrix.config }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}

      - name: Bazel info (discover paths)
        id: bazel-info
        run: |
          echo "BAZEL_OUTPUT_BASE=$(bazel info output_base)" >> $GITHUB_ENV
          echo "BAZEL_USER_ROOT=$(bazel info output_user_root)" >> $GITHUB_ENV
          echo "BAZEL_REPO_CACHE=$(bazel info repository_cache)" >> $GITHUB_ENV
          bazel info

      - name: Build with Bazel
        run: |
          bazel build --lockfile_mode=error --config ${{ matrix.config }} //src/... //examples/...
